import {
  Container,
  Text,
  Spacer,
  Grid,
  Card,
  Link,
  Row,
} from "@nextui-org/react";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Index() {
  return (
    <main>
      <Container>
        <Spacer y={6} />
        <Text
          h1
          size={80}
          weight="black"
          css={{
            textAlign: "center",
            lineHeight: 1.2,
          }}
        >
          Make the <br />
          Open Source <br />
          Better
        </Text>
        <Spacer y={6} />
      </Container>
      <Container sm>
        <Grid.Container gap={2} justify="center">
          <Grid xs={6}>
            <Card variant="bordered">
              <Card.Body>
                <Text h4>For Companies</Text>
                <Text>
                  Would you like your company to be part of this initiative?
                  Find out how you can join now.
                </Text>
              </Card.Body>
              <Card.Footer>
                <Link icon size="sm">
                  Find out more
                </Link>
              </Card.Footer>
            </Card>
          </Grid>
          <Grid xs={6}>
            <Card variant="bordered">
              <Card.Body>
                <Text h4>For OS</Text>
                <Text>
                  Would you like to get help with you Open Source project, by
                  the actual users? Find out how we can help.
                </Text>
              </Card.Body>
              <Card.Footer>
                <Link icon size="sm">
                  Find out more
                </Link>
              </Card.Footer>
            </Card>
          </Grid>
        </Grid.Container>
      </Container>
    </main>
  );
}
